### ISSUE TITLE
Uploading file to wrong directory on multisite 

### ISSUE THREAD

**Issue by josephbydeign** [JoeSz/Exopite-Simple-Options-Framework#13]
When using Exopite-Simple-Options-Framework on a subsite on a multisite network it uploads the image to the right directory but gives it the wrong URL. It works fine on the main network site.

### Example

Upload image using metabox, it gives it the url of `/sites/4/sites/4/` instead of just `/sites/4/`

<img width="691" alt="screenshot 2018-12-05 at 11 09 08" src="https://user-images.githubusercontent.com/11774156/49530716-69d5ff00-f87e-11e8-8ad8-05c48b57f6c5.png">

manually changing the URL works

<img width="637" alt="screenshot 2018-12-05 at 11 10 10" src="https://user-images.githubusercontent.com/11774156/49530847-adc90400-f87e-11e8-89e3-eb3d9243c211.png">

Even though it is returning the wrong URL when called it is uploading it to the correct directory of `/sites/4/`

<img width="479" alt="screenshot 2018-12-05 at 11 13 56" src="https://user-images.githubusercontent.com/11774156/49530973-e7017400-f87e-11e8-91ab-2be7a9f6d894.png">

**Comment by JoeSz** [comment]
Thank you for the Info.
I will take a look, I didn't tested in multisite. It may take time though.

Joe

On Wed, 05 Dec 2018 18:17:40 +0100, Joseph VanTine  
<notifications@github.com> wrote:

>
> When using Exopite-Simple-Options-Framework on a subsite on a multisite  
> network it uploads the image to the right directory but gives it the  
> wrong >URL. It works fine on the main network site.
> Example
>
> Upload image using metabox, it gives it the url of /sites/4/sites/4/  
> instead of just /sites/4/
>
>
>
> manually changing the URL works
>
>
>
> Even though it is returning the wrong URL when called it is uploading it  
> to the correct directory of /sites/4/
>
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Using Opera's mail client: http://www.opera.com/mail/

**Comment by josephbydeign** [comment]
#14 added fix. Not only was it breaking WPMU but also standard sites as well, causing me to believe it was caused by a Wordpress update.

**Comment by JoeSz** [comment]
Thank you!
