### ISSUE TITLE
Undefined index id on line 1248 in exopite-simple-options-framework-class.php

### ISSUE THREAD

**Issue by kwatts22** [JoeSz/Exopite-Simple-Options-Framework#19]
Getting this error when loading the framework. It shows 

Undefined index id on line 1248 in exopite-simple-options-framework-class.php

**Comment by JoeSz** [comment]
Please paste your config here. Which version do you use?

**Comment by kwatts22** [comment]
Trying to upgrade to version 20190527. I am currently using the older version in a wordpress boilerplate plugin.

**Comment by JoeSz** [comment]
Did you tried it? Is it working?

**Comment by omgwtfwow** [comment]
Hey @JoeSz this seems to happen when you have a group/fieldset array without an ID. I was getting a similar error and fixed it by adding an ID to that menu item.

**Comment by omgwtfwow** [comment]
Actually, spoke too soon, still have the issue.
[https://github.com/omgwtfwow/all-in-one-analytics/issues/1#issue-467640048](url) 

My config here https://github.com/omgwtfwow/all-in-one-analytics/blob/9a8e2a3d6166852e02b11822f24f0ae8d55556f9/admin/class-all-in-one-analytics-admin.php

**Comment by JoeSz** [comment]
Sorry it took so long, but now it is fixed.

**Comment by JoeSz** [comment]
I didn't see your responds after the issue was closed :(
