### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by josephbydeign** [JoeSz/Exopite-Simple-Options-Framework#2]
Hi Joe, 

I have some documentation questions regarding some of the fields, I was wondering if you would be ok to answer them. Mainly with `attached`, `upload`, and `video`.

I know you said the documentation is still in progress, maybe we could work together on the documentation as I really love this plugin and also the plugin boilerplate. 

Feel free to delete this issue and message me on twitter [@yobddigi](https://twitter.com/yobddigi)

Cheers

**Comment by JoeSz** [comment]
"I know you said the documentation is still in progress, maybe we could work together on the documentation as I really love this plugin and also the plugin boilerplate."
Sounds great :) 

I'm currently working on WPML, Polylang and qTranslate-X support for the framework, but
unfortunaly I have little time (My wife and I got a baby), if I have any, then mostly on weekends.
But I will do my best :)

**Comment by josephbydeign** [comment]
Awesome! If you contact me on twitter I can send you my email address which would be better than here
