### ISSUE TITLE
Feedback when submitting to WP plugin repo

### ISSUE THREAD

**Issue by omgwtfwow** [JoeSz/Exopite-Simple-Options-Framework#20]
Hi, thank you so much for this.

Just letting you know some feedback.

I submitted a plugin to the WordPress repo and initially it got pushed back because of some sanitation issues with the options framework.

> ## Please sanitize, escape, and validate your POST calls 
> 
> When you include POST/GET/REQUEST/FILE calls in your plugin, it's important to sanitize, validate, and escape them. The goal here is to prevent a user from accidentally sending trash data through the system, as well as protecting them from potential security issues.
> 
> Some examples from your plugin:
> 
> segment-for-wordpress/admin/exopite-simple-options/exopite-simple-options-framework-class.php:1040:
> $posted_data = $_POST[ $this->unique ];

I mentioned the use of the class Exopite_Simple_Options_Framework_Sanitize further down, but they insisted.

> In general, reinventing the wheel with sanitization is to be avoided. It's not an effective use of your time, given that WordPress already has a lot of sanitization options available.
> 
> And you're neglecting code like this:

In the end I had to add a couple of extra sanitation that I thought was irrelevant, but they seem to need/want to get the plugin in the WP repo.
things like:

> segment-for-wordpress/admin/exopite-simple-options/exopite-simple-options-framework-class.php:1040:
> $posted_data = absint($_POST[ $this->unique ]);

I think maybe it's because it was the first plugin I submitted. After some small additions of sanitising checks like the one above the plugin got approved.

Anyway thanks again!

**Comment by JoeSz** [comment]
Hi, sorry for the late answer, I was in vacation. Could you please send me the modified framework to joe@joeszalai.org, so I can see which extra sanitation is required and implement them? (or make a pull request?)

**Comment by omgwtfwow** [comment]
Just as an update, I submitted a second plugin that did not get flagged for any sanitation issues with the options framework. So I think it was just an automated check/message.

**Comment by JoeSz** [comment]
Thank you for the infos and the update! I wish everyone would do that. :)
I was surprised because the framework does sanitize, escape, and validate. And it was not easy to implement :D
