### ISSUE TITLE
Group & Repeater 

### ISSUE THREAD

**Issue by KarmaQuest** [JoeSz/Exopite-Simple-Options-Framework#23]
Hi JoeSz, 

When I create a repeater field in another repeater field,  my INPUT fields become DISABLED into the repeater (but i  create a clone without disabled) 

![ScreenBug](https://user-images.githubusercontent.com/58166027/69525651-2991f400-0f9b-11ea-8d5a-3aea80813b21.png)

Could you help me ? ='( 

Nice Day

**Comment by JoeSz** [comment]
Can you please paste your options here?

**Comment by KarmaQuest** [comment]
Hello, 
My first repeater is here : 
![image](https://user-images.githubusercontent.com/58166027/69598238-454cd700-103b-11ea-82b2-10e0981d333f.png)

And the repeater who have the field disabled is here : 
![image](https://user-images.githubusercontent.com/58166027/69598274-64e3ff80-103b-11ea-8881-7aee1b8aaf0b.png)

Here all my code from the repeater : 
<code> 
array(
                            'title'  => '<i class="fa fa-superpowers" aria-hidden="true"></i> ' . esc_html__( 'Frappe Gantt', 'wpdatavisualisation' ),
                            'fields' => array(
                                array(
                                    'id'      => 'switcher_datavisu_4',
                                    'type'    => 'switcher',
                                    'title'   => 'Frappe Gantt',
                                    'label'   => 'Frappe Gantt',
                                    'default' => 'no',
                                ),

                                array(
                                    'type'    => 'group',
                                    'id'      => 'group_gantt_sortable',
                                    'options' => array(
                                        'repeater'          => true,
                                        'accordion'         => true,
                                        'button_title'      => esc_html__( 'Add new', 'wpdatavisualisation' ),
                                        'group_title'       => esc_html__( 'Accordion Title', 'wpdatavisualisatione' ),
                                        'limit'             => 50,
                                        'sortable'          => true,
                                        'mode'              => 'compact',
                                    ),
                                    'fields'  => array(

                                        array(
                                            'id'      => 'group_gantt_sortable_text_1',
                                            'type'    => 'text',
                                            'attributes' => array(
                                                // mark this field az title, on type this will change group item title
                                                'data-title' => 'title',
                                                'placeholder' => esc_html__( 'Title Task', 'wpdatavisualisatione' ),
                                            ),
                                        ),

                                        array(
                                            'id'     => 'date_groupe_frappe_gantt_sortable_1',
                                            'type'   => 'date',
                                            'title'  => 'Start Date',
                                            'format' => 'yy-mm-dd',
                                            'class'  => 'datepic-class',
                                            'prepend' => 'fa-calendar',
                                        ),

                                        array(
                                            'id'     => 'date_groupe_frappe_gantt_sortable_2',
                                            'type'   => 'date',
                                            'title'  => 'End Date',
                                            'format' => 'yy-mm-dd',
                                            'class'  => 'datepic-class',
                                            'prepend' => 'fa-calendar',
                                        ),
                                        array(
                                            'id'      => 'group_gantt_sortable_progression',
                                            'type'    => 'number',
                                            'attributes' => array(
                                                // mark this field az title, on type this will change group item title
                                                'data-title' => 'title',
                                                'placeholder' => esc_html__( 'Progression', 'wpdatavisualisatione' ),
                                            ),
                                        ),



                                        array(
                                            'type'    => 'group',
                                            'id'      => 'group_gantt_sortable_dependencies',
                                            'title'   => esc_html__( 'Add Sub-Task', 'wpdatavisualisation' ),
                                            'options' => array(
                                                'group_title'       => esc_html__( 'Dependence Title', 'plugin-name' ),
                                                'repeater'          => true,
                                                'cloneable'    	=> false,
                                                'button_title'      => esc_html__( 'Add new Dependancies', 'plugin-name' ),
                                                'limit'        	=> 25,
                                            ),
                                            'fields'  => array(

                                                    array(
                                                        'id'      => 'group_gantt_sortable_text_dependencies',
                                                        'type'    => 'text',
                                                        'attributes' => array(
                                                            'placeholder' => esc_html__( 'Title Task Dépendencies', 'wpdatavisualisatione' ),
                                                            'disabled' => false

                                                        ),
                                                    ),

                                                    array(
                                                        'id'     => 'date_groupe_frappe_gantt_sortable_dependencies',
                                                        'type'   => 'date',
                                                        'title'  => 'Start Date Dépendencies',
                                                        'format' => 'yy-mm-dd',
                                                        'class'  => 'datepic-class',
                                                        'prepend' => 'fa-calendar',
                                                        'attributes' => array(
                                                            // mark this field az title, on type this will change group item title
                                                            'disabled' => false
                                                        ),
                                                    ),

                                                    array(
                                                        'id'     => 'date_groupe_frappe_gantt_sortable_dependencies',
                                                        'type'   => 'date',
                                                        'title'  => 'End Date Dépendencies',
                                                        'format' => 'yy-mm-dd',
                                                        'class'  => 'datepic-class',
                                                        'prepend' => 'fa-calendar',
                                                        'attributes' => array(
                                                            // mark this field az title, on type this will change group item title
                                                            'disabled' => false
                                                        ),
                                                    ),
                                                    array(
                                                        'id'      => 'group_gantt_sortable_progression_dependencies',
                                                        'type'    => 'number',
                                                        'attributes' => array(
                                                            // mark this field az title, on type this will change group item title
                                                            'placeholder' => esc_html__( 'Progression Dépendencies', 'wpdatavisualisatione' ),
                                                            'disabled' => false
                                                        ),
                                                    ),
                                            ),
                                        ),
                                    ),
                                ),
                            ),
                        ), </code>

**Comment by KarmaQuest** [comment]
I do not know if you have had time to look. 
But would not that come from the many Jquery files present ?

I try to edit the php sheet Group, and I make disappear the attribute with a unset. 
But the fields are still disabled :'(

**Comment by JoeSz** [comment]
No, I did not have any Time yet. I'm in vacation, still a lot to do. I will take a look in the next few days.

**Comment by KarmaQuest** [comment]
No problem, enjoy your vacation =) 

It's a great project, the force is with you

**Comment by JoeSz** [comment]
Ok, I know what is the problem. The first item is always the "template" for cloning. It has to exist for the JavaScript to clone. It should be invisible, but I think I made some mistake with the CSS and this is now visible. It need to be disabled, so the form does not submitting the template fields. 

Please update your framework. And let me know, if it is working or not :)

**Comment by KarmaQuest** [comment]
Wow, it's ok after the update ! Thank you Joe :) 
![image](https://user-images.githubusercontent.com/58166027/69909538-d56d9080-142e-11ea-9393-05df45dc9d88.png)

You have a great idea with this plugin !

**Comment by KarmaQuest** [comment]
I don't want to abuse, but now, when you publish a custom post type, you have problem with the Class Exopite_Simple_Options_Framework_Sanitize : 

![image](https://user-images.githubusercontent.com/58166027/69910324-65660700-143c-11ea-9660-2dcc9e96d84d.png)

**Comment by JoeSz** [comment]
Could you please more specific? Do you think it is because the CPT?

**Comment by JoeSz** [comment]
You are not "abuse" :) I'm happy, I have feedback, because I can not test everything. The framework already working on a lot of sites, but it takes time to perfect it. Of course, in Christmas time, everything takes longer too. ;)

**Comment by JoeSz** [comment]
Two comment on the options:
- you have to id "date_groupe_frappe_gantt_sortable_dependencies" two times. ID need to be unique,
- 'disabled' => false make field disabled, beacuse it is making an HTML attibute

**Comment by JoeSz** [comment]
I fixed the PHP warnings too.

**Comment by JoeSz** [comment]
Due to lack of feedback I assume it works;)
