### ISSUE TITLE
 .zip from https://github.com/JoeSz/WordPress-Plugin-Boilerplate-Tutorial does not work

### ISSUE THREAD

**Issue by jorgenfhlarsen** [JoeSz/Exopite-Simple-Options-Framework#25]
Hi

I hope you can fix:

https://github.com/JoeSz/WordPress-Plugin-Boilerplate-Tutorial

so that when cloned can be installed directly ???

Thank you in advance.

/Jørgen

**Comment by JoeSz** [comment]
Hi, 
you have to find the "plugin-name" and this folder need to copy to the /wp-content/plugins/ folder.
Just upload the zip file will not work.
I do not want to change the zip content, becuase I want some structure.
Joe
