### ISSUE TITLE
Does this framework support conditional fields?

### ISSUE THREAD

**Issue by azadrpi** [JoeSz/Exopite-Simple-Options-Framework#26]
Hi Joe,

Thanks a lot to make this awesome options framework. I really loved! I appreciate your hard works & making it available for free.

I was wondering if this framework supports loading a field which is depend on another field?

Thanks!
Azad

**Comment by JoeSz** [comment]
Hi Azad,

in theory yes. But normally you have to create a filed which support that.
The Tab, Group and Fieldset field already does that.
You can take a look for more information.

Also if you provide a little more information, what (or how) exactly you  
want to accomplish here, maybe I can help more.

Regards,

Joe

**Comment by azadrpi** [comment]
Thanks for your reply. 

I've checked that The Tab, Group and Fieldset field, but didn't notice that I'm looking for. Maybe you've missed my point. Please check below.

For example, I have 3 options.
1. Background Type (this is a select field. has 2 options named "Image" & "Color"
2. Upload Image (I want to show this field when user select "image" & hide when select "Color")
3. Select Color (I want to show this field when user select "color" & hide when select "Image")

Hope this scenario will help you to understand my requirements.

**Comment by JoeSz** [comment]
Sorry for the late answer. You could take a look in typography field. For hide fields inside custom field, you have to write your own JavaScript.
