### ISSUE TITLE
Is it possible to put Exopite-Simple-Options-Framework through the Composer?

### ISSUE THREAD

**Issue by RobertGard** [JoeSz/Exopite-Simple-Options-Framework#28]
Can I put this plugin https://github.com/JoeSz/Exopite-Simple-Options-Framework through Composer?

**Comment by JoeSz** [comment]
I have no idea, I never tried. But if you do it, can you please share how?

**Comment by RobertGard** [comment]
Why this trolling?

**Comment by JoeSz** [comment]
I don't understand what you mean?
