### ISSUE TITLE
Instead of init you can use admin_menu

### ISSUE THREAD

**Issue by kmiskiewicz** [JoeSz/Exopite-Simple-Options-Framework#30]
Hey, instead of adding the code to 'init' action you can use 'admin_menu' with priority 0. Adding to 'init' means that the code will be called also for not logged in WP users
e.g.
$this->loader->add_action('admin_menu', $plugin_admin, 'create_menu',0);

**Comment by JoeSz** [comment]
Hi :)
You are absolutely right. But you mean the Plugin Boilerplate Tutorial not the Simple Options Framework,. right?
Can you please create a pull request?
Joe
