### ISSUE TITLE
Uploads are not sticking

### ISSUE THREAD

**Issue by MilesS** [JoeSz/Exopite-Simple-Options-Framework#35]
For admin panels the uploads are not staying.

Example: I upload an image, and save.

<img width="1486" alt="Screen Shot 2021-02-02 at 1 31 39 PM" src="https://user-images.githubusercontent.com/2748096/106674927-f5d03800-6568-11eb-9fe5-ce7fd54fe0f2.png">

I refresh the page and there are no uploads in the dashboard.

<img width="1456" alt="Screen Shot 2021-02-02 at 1 31 25 PM" src="https://user-images.githubusercontent.com/2748096/106674937-f799fb80-6568-11eb-8e64-ac3d93e59778.png">

However, the files have added to wp-content/uploads/

If this can't be fixed for panels is a proper way to override the folder that the system uploads. Rather than putting it into wp-content/uploads/year/month having it be wp-content/uploads/my-plugin.

**Comment by JoeSz** [comment]
Hi,

the upload panel does not show uploded images. You have to use an other element for it, eg.: the gallery element.
The Upload element purpose is to upload, not to show.

The Framework use the wp_upload_dir function from WordPress. You could override it:
https://wordpress.stackexchange.com/a/261933/90212
https://developer.wordpress.org/reference/functions/wp_upload_dir/

If you wish, I can also add a filter to override this. I thought, I leave it in the WordPress way.

**Comment by MilesS** [comment]
Got it.

I am guessing the upload has some sort of return I can hook into, so I can document the uploaded files in the database to be able to retrieve the documents for something like a gallery?

I am assuming since it is upload only it doesn't store any metadata.

I guess I will just have to dive more into the code.

**Comment by JoeSz** [comment]
I think you already solved this :) 
If somebody want to know:
[Wordpress: Get images of current post](https://stackoverflow.com/questions/12230928/wordpress-get-images-of-current-post)
