### ISSUE TITLE
Get option value of group item

### ISSUE THREAD

**Issue by AGhilHz** [JoeSz/Exopite-Simple-Options-Framework#37]
Hi
I want use group type in my plugin Option to add items by user ( add some of clients.. )
I created this options in admin area, but i dont know how to get values, return in front and display in my website..
please help me.

this is my options for define **Clients** :

`                array(
                    'type' => 'group',
                    'id' => 'hwtm-header-clients-group',
                    'title' => __('Clients', 'tooska'),
                    'description' => __('Our Clients.', 'tooska'),
                    'options' => array(
                        'repeater' => true,
                        'accordion' => true,
                        'button_title' => __('New client', 'tooska'),
                        'group_title' => __('Clients', 'tooska'),
                        'limit' => 20,
                        'sortable' => true,
                    ),
                    'fields' => array(

                        array(
                            'id' => 'hwtm-header-clients-source',
                            'type' => 'image',
                            'title' => __('Client Logo', 'tooska'),
                            'attributes' => array(
                                'data-title' => 'title',
                                'placeholder' => __('For example: ' . home_url() . '/redirect-from', 'tooska'),
                                'class' =>  'hwtm-ltr hwtm-redirect',
                                'required'  =>  'required'
                            ),
                        ),
                        array(
                            'id' => 'hwtm-header-clients-target',
                            'type' => 'text',
                            'title' => __('Link', 'tooska'),
                            'attributes' => array(
                                'data-title' => 'title',
                                'placeholder' => __('for example: ' . home_url() . '/redirect-to', 'tooska'),
                                'pattern' => esc_html__('https?://.+', 'tooska'),
                                'class' =>  'hwtm-ltr hwtm-redirect',
                                'required'  =>  'required'
                            ),
                        ),
                        array(
                            'id' => 'hwtm-header-clients-name',
                            'type' => 'text',
                            'title' => __('Client name', 'tooska'),
                            'attributes' => array(
                                'data-title' => 'title',
                                'class' =>  'hwtm-ltr hwtm-redirect',
                                'required'  =>  'required'
                            ),
                        ),
                        $redirect_status_text
                    ),
                ),`

**Comment by JoeSz** [comment]
From description:
```php
$my_options = get_option( 'my-plugin-slug' );
if ( $my_options[$current_lang]['my-option-name'] ) {
    // code...
}
```
so in your case should be this (e.g.):

```php
// I do not know your option slug and language
$my_options = get_option( 'my-plugin-slug');

// repeater (as far as I remember), 0 is the index of the repeated field(s)
$my_options[$current_lang]['hwtm-header-clients-group'][0]['hwtm-header-clients-source'];

// but you can see all options if you e.g. var_export them:
var_export( $my_options );
```

**Comment by AGhilHz** [comment]
thanks
i use this code and wirked for me:
`	foreach ( $options['hwtm-clients-group'] as $clients_options ) {
		echo '
							<div class="slide">
								<a href="'.$clients_options['hwtm-clients-link'].'" target="_blank" rel="noreferrer" aria-label="Brand">                   
									<img data-lazyloaded="1" data-placeholder-resp="150x150" src="'.$clients_options['hwtm-clients-logo'].'"
									 alt="'.$clients_options['hwtm-clients-name'].'" width="150" height="150">
								</a>
							</div>
		';
	}`

**Comment by JoeSz** [comment]
no worries :)
