### ISSUE TITLE
Why html tags in TinyMCE editor are removing?

### ISSUE THREAD

**Issue by KingMatrix1989** [JoeSz/Exopite-Simple-Options-Framework#38]
Hi. It seems content of editor field of type TinyMCE (default) is sanitized after save options and html tags is removing.

Why?

**Comment by JoeSz** [comment]
I just installed a clean WordPress with the test plugin. 
I couldn't reproduce it.
Which version are you using? Which HTML tag is the problem?

Allowed HTML tags:
(https://developer.wordpress.org/reference/functions/wp_kses_allowed_html/)
```php
$allowed_html = wp_kses_allowed_html( 'post' );
```

And you can also override (add your own) sanitizing hook to the field.
For example:
```php
array(
    'id'          => 'text_1',
    'type'   => 'editor',
    'title'  => 'Editor TinyMCE',
    'sanitize'    => array( $this, 'test_sanitize_callback' ),
    ...
),
```

**Comment by JoeSz** [comment]
Closing issue due to lack of response.
